"""empty message

Revision ID: 1a02f1b6396b
Revises: 0e0a415da173
Create Date: 2021-06-26 08:50:57.108993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a02f1b6396b'
down_revision = '0e0a415da173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed_list', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'completed_list')
    # ### end Alembic commands ###
