"""empty message

Revision ID: e1c5ed1cd1cd
Revises: 1f5f7a9fdca6
Create Date: 2021-05-20 22:33:40.617799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c5ed1cd1cd'
down_revision = '1f5f7a9fdca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    ######### here, we change "False" to "True", to avoid the error
    ####### the error is when you add new record on 'description' you may not add values to 'completed'
    #### if no value in 'completed', the default is Null. this contradicts with the app.py's 'completed' value
    ## therefore, we need manually change the 'completed' default contrain from 'non nullable' to 'nullable'
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    ### could manually edit the version .py and make the changes

    ## and then, we manually insert the completed default value as False
    ## as the value is false, the nullable is false (not true, it has values, not null)
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')

    ## then change back the nullable to false
    op.alter_column('todos', 'completed', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
